[[headers]]
  for = "/playground"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/playground/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Resource-Policy = "cross-origin"
